#!/bin/bash

#Script to grab forensics artifacts on linux machines with Bash


#Time
timeCurrent=$(date +"%T")
timeZone=$(date +"%Z")
timeUptime=$(uptime -p)

echo 'Time'
echo 'Current time: '$timeCurrent
echo 'Timezone: '$timeZone
echo 'Uptime: '${timeUptime}

#OS Version
osNumber=$(uname -r)
osName=$(uname -s)
osKernelVersion=$(uname -r)

echo
echo 'OS Version'
echo 'Current OS Version: '$osNumber
echo 'Current OS Name: '$osName
echo 'Current Kernel Version: '$osKernelVersion

#Hardware
cpu=$(cat /proc/cpuinfo | grep 'model name')
cpu=$(echo $cpu | sed 's/.*://')
ramTotal=$(grep MemTotal /proc/meminfo)
totalHDD=$(df -k . -h)
totalHDD=$(echo $totalHDD | sed 's/.*rootfs //' | head -n1 | awk '{print $1;}')
#List hdds
#list mounted file systems
mounted=$(ls /mnt)


echo
echo 'CPU: '$cpu
echo $ramTotal
echo 'Storage Space Total: '$totalHDD
echo 'Mounted File Systems: '$mounted

#Domain controller

#Hostname and Domain
hostname=$(hostname)
domainname=$(domainname)

echo
echo 'Hostname: '$hostname
echo 'Domain Name: '$domainname

#users

#boot

#scheduled tasks

#Network
arptable=$(arp)
#mac address for all interfaces
mac=$(ip a | grep -o "link/[a-z0-9.]* [a-f0-9]*\:[a-f0-9]*\:[a-f0-9]*\:[a-f0-9]*\:[a-f0-9]*\:[a-f0-9]*" | grep -o "[a-f0-9]*\:[a-f0-9]*\:[a-f0-9]*\:[a-f0-9]*\:[a-f0-9]*\:[a-f0-9]*")
#routing table
routingtable=$(route)
#ip addresses for all interfaces
ipv4=$(ip addr show | grep -o "inet [0-9]*\.[0-9]*\.[0-9]*\.[0-9]*" | grep -o "[0-9]*\.[0-9]*\.[0-9]*\.[0-9]*")
ipv6=$(ip addr show | grep -o "inet6 [a-f0-9:]*" | cut -c 6-)
#find dhcp server
#dhcp=$(
#find dns server
dns=$(cat /etc/resolv.conf | grep -o "[0-9]*\.[0-9]*\.[0-9]*\.[0-9]*")
#find gateways
gateways=$(route -n | grep '[ \t]' | awk '{print $2}' | grep -o "[0-9]*\.[0-9]*\.[0-9]*\.[0-9]*")
#listening services
#	ip addr bound to
#	port
#	protocol
#	service/process name
#connections
#	remote ip
#	local/remote port
#	protocol
#	timestamp
#	service/process name
#dns cache

echo
echo 'Arp Table: '
arp
echo 'MAC Addresses: '$mac
echo 'Routing Table: '
route
echo
echo 'IPv4 Addresses: '$ipv4
echo 'IPv6 Addresses: '$ipv6
echo 'DHCP Server: '
echo 'DNS Servers: '$dns
echo 'Gateways: '$gateways

#network shares, printers, and wifi profiles

#list of all installed software
#compgen -c
#process list

#Driver list

#list of files in downloads and documents for each user directory

#three custom (PATH, BASH location, BASH version)
echo
echo 'Path: '$PATH
echo 'Bash Location: '$BASH
echo 'Bash Version: '$BASH_VERSION

